
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/bsm/go-vlq"

[[constraint]]
  branch = "master"
  name = "github.com/martinboehm/btcd"

[[constraint]]
  branch = "master"
  name = "github.com/martinboehm/btcutil"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  branch = "master"
  name = "github.com/juju/errors"

[[constraint]]
  branch = "master"
  name = "github.com/martinboehm/golang-socketio"

[[constraint]]
  branch = "master"
  name = "github.com/pebbe/zmq4"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/tecbot/gorocksdb"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.2"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/martinboehm/bchutil"
